version = 1
SPDX-PackageName = "Capellambse Context Diagrams"
SPDX-PackageSupplier = "Ernst Würger <ernst.wuerger@deutschebahn.com>"
SPDX-PackageDownloadLocation = "https://github.com/DSD-DBS/capellambse-context-diagrams"

[[annotations]]
path = "tests/data/elk_input/**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright DB InfraGO AG and the capellambse-context-diagrams contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "tests/data/elk_layout/**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright DB InfraGO AG and the capellambse-context-diagrams contributors"
SPDX-License-Identifier = "CC0-1.0"
